#pragma once
#ifndef SHOTACTIONTYPES_H
#define SHOTACTIONTYPES_H

#include <QHash>
#include <QSet>
#include <QString>
#include <QColor>

enum EShotActionType {
    EShotUnknown,
    EShotCam,
    EShotCamBlendStart,
    EShotCamBlendKey,
    EShotCamBlendEnd,
    EShotCamBlendTogame,
    EShotActorAnim,
    EShotActorAnimAdditive,
    EShotActorAnimPose,
    EShotActorMimicAnim,
    EShotActorMimicPose,
    EShotActorPlacement,
    EShotActorPlacementStart,
    EShotActorPlacementKey,
    EShotActorPlacementEnd,
    EShotActorGamestate,
    EShotActorLookat,
    EShotActorScabbardShow,
    EShotActorScabbardHide,
    EShotActorShow,
    EShotActorHide,
    EShotActorEffectStart,
    EShotActorEffectStop,
    EShotActorSound,
    EShotActorAppearance,
    EShotActorEquipRight,
    EShotActorEquipLeft,
    EShotActorUnequipRight,
    EShotActorUnequipLeft,
    EShotPropShow,
    EShotPropHide,
    EShotPropPlacement,
    EShotPropPlacementStart,
    EShotPropPlacementKey,
    EShotPropPlacementEnd,
    EShotPropEffectStart,
    EShotPropEffectStop,
    EShotEnvBlendIn,
    EShotEnvBlendOut,
    EShotFadeIn,
    EShotFadeOut,
    EShotWorldAddfact,
    EShotWorldWeather,
    EShotWorldEffectStart,
    EShotWorldEffectStop,
};

const QHash<QString, EShotActionType> stringToEShotAction = {
    { "cam",                    EShotCam                },
    { "cam.blend.start",        EShotCamBlendStart      },
    { "cam.blend.key",          EShotCamBlendKey        },
    { "cam.blend.end",          EShotCamBlendEnd        },
    { "cam.blend.togame",       EShotCamBlendTogame     },
    { "env.blendin",            EShotEnvBlendIn         },
    { "env.blendout",           EShotEnvBlendOut        },
    { "fade.in",                EShotFadeIn             },
    { "fade.out",               EShotFadeOut            },
    { "world.addfact",          EShotWorldAddfact       },
    { "world.weather",          EShotWorldWeather       },
    { "world.effect.start",     EShotWorldEffectStart   },
    { "world.effect.stop",      EShotWorldEffectStop    },
    { "actor.anim",             EShotActorAnim          },
    { "anim",                   EShotActorAnim          },
    { "actor.anim.additive",    EShotActorAnimAdditive  },
    { "anim.additive",          EShotActorAnimAdditive  },
    { "actor.pose",             EShotActorAnimPose      },
    { "actor.anim.mimic",       EShotActorMimicAnim     },
    { "anim.mimic",             EShotActorMimicAnim     },
    { "actor.mimic",            EShotActorMimicPose     },
    { "actor.placement",        EShotActorPlacement     },
    { "actor.placement.start",  EShotActorPlacementStart},
    { "actor.placement.key",    EShotActorPlacementKey  },
    { "actor.placement.end",    EShotActorPlacementEnd  },
    { "actor.gamestate",        EShotActorGamestate     },
    { "actor.lookat",           EShotActorLookat        },
    { "actor.scabbard.show",    EShotActorScabbardShow  },
    { "actor.scabbard.hide",    EShotActorScabbardHide  },
    { "actor.show",             EShotActorShow          },
    { "actor.hide",             EShotActorHide          },
    { "actor.effect.start",     EShotActorEffectStart   },
    { "actor.effect.stop",      EShotActorEffectStop    },
    { "actor.sound",            EShotActorSound         },
    { "actor.appearance",       EShotActorAppearance    },
    { "actor.equip.right",      EShotActorEquipRight    },
    { "actor.equip.left",       EShotActorEquipLeft     },
    { "actor.unequip.right",    EShotActorUnequipRight  },
    { "actor.unequip.left",     EShotActorUnequipLeft   },
    { "prop.show",              EShotPropShow           },
    { "prop.hide",              EShotPropHide           },
    { "prop.effect.start",      EShotPropEffectStart    },
    { "prop.effect.stop",       EShotPropEffectStop     },
    { "prop.placement",         EShotPropPlacement      },
    { "prop.placement.start",   EShotPropPlacementStart },
    { "prop.placement.key",     EShotPropPlacementKey   },
    { "prop.placement.end",     EShotPropPlacementEnd   }
};
const QHash<EShotActionType, QString> EShotActionToString = {
    { EShotCam,                 "cam"                   },
    { EShotCamBlendStart,       "cam.blend.start"       },
    { EShotCamBlendKey,         "cam.blend.key"         },
    { EShotCamBlendEnd,         "cam.blend.end"         },
    { EShotCamBlendTogame,      "cam.blend.togame"      },
    { EShotEnvBlendIn,          "env.blendin"           },
    { EShotEnvBlendOut,         "env.blendout"          },
    { EShotFadeIn,              "fade.in"               },
    { EShotFadeOut,             "fade.out"              },
    { EShotWorldAddfact,        "world.addfact"         },
    { EShotWorldWeather,        "world.weather"         },
    { EShotWorldEffectStart,    "world.effect.start"    },
    { EShotWorldEffectStop,     "world.effect.stop"     },
    { EShotActorAnim,           "actor.anim"            },
    { EShotActorAnimAdditive,   "actor.anim.additive"   },
    { EShotActorAnimPose,       "actor.pose"            },
    { EShotActorMimicAnim,      "actor.anim.mimic"      },
    { EShotActorMimicPose,      "actor.mimic"           },
    { EShotActorPlacement,      "actor.placement"       },
    { EShotActorPlacementStart, "actor.placement.start" },
    { EShotActorPlacementKey,   "actor.placement.key"   },
    { EShotActorPlacementEnd,   "actor.placement.end"   },
    { EShotActorGamestate,      "actor.gamestate"       },
    { EShotActorLookat,         "actor.lookat"          },
    { EShotActorScabbardShow,   "actor.scabbard.show"   },
    { EShotActorScabbardHide,   "actor.scabbard.hide"   },
    { EShotActorShow,           "actor.show"            },
    { EShotActorHide,           "actor.hide"            },
    { EShotActorEffectStart,    "actor.effect.start"    },
    { EShotActorEffectStop,     "actor.effect.stop"     },
    { EShotActorSound,          "actor.sound"           },
    { EShotActorAppearance,     "actor.appearance"      },
    { EShotActorEquipRight,     "actor.equip.right"     },
    { EShotActorEquipLeft,      "actor.equip.left"      },
    { EShotActorUnequipRight,   "actor.unequip.right"   },
    { EShotActorUnequipLeft,    "actor.unequip.left"    },
    { EShotPropShow,            "prop.show"             },
    { EShotPropHide,            "prop.hide"             },
    { EShotPropEffectStart,     "prop.effect.start"     },
    { EShotPropEffectStop,      "prop.effect.stop"      },
    { EShotPropPlacement,       "prop.placement"        },
    { EShotPropPlacementStart,  "prop.placement.start"  },
    { EShotPropPlacementKey,    "prop.placement.key"    },
    { EShotPropPlacementEnd,    "prop.placement.end"    }
};
const QHash<EShotActionType, int> EShotActionToGroupNum = {
    { EShotCam,                 0   },
    { EShotCamBlendStart,       0   },
    { EShotCamBlendKey,         0   },
    { EShotCamBlendEnd,         0   },
    { EShotCamBlendTogame,      0   },
    { EShotEnvBlendIn,          1   },
    { EShotEnvBlendOut,         1   },
    { EShotFadeIn,              1   },
    { EShotFadeOut,             1   },
    { EShotWorldAddfact,        1   },
    { EShotWorldWeather,        1   },
    { EShotWorldEffectStart,    1   },
    { EShotWorldEffectStop,     1   },
    { EShotActorAnim,           1   },
    { EShotActorAnimAdditive,   2   },
    { EShotActorAnimPose,       2   },
    { EShotActorMimicAnim,      3   },
    { EShotActorMimicPose,      3   },
    { EShotActorPlacement,      5   },
    { EShotActorPlacementStart, 5   },
    { EShotActorPlacementKey,   5   },
    { EShotActorPlacementEnd,   5   },
    { EShotActorGamestate,      0   },
    { EShotActorLookat,         4   },
    { EShotActorScabbardShow,   0   },
    { EShotActorScabbardHide,   0   },
    { EShotActorShow,           0   },
    { EShotActorHide,           0   },
    { EShotActorEffectStart,    6   },
    { EShotActorEffectStop,     6   },
    { EShotActorSound,          6   },
    { EShotActorAppearance,     0   },
    { EShotActorEquipRight,     0   },
    { EShotActorEquipLeft,      0   },
    { EShotActorUnequipRight,   0   },
    { EShotActorUnequipLeft,    0   },
    { EShotPropShow,            0   },
    { EShotPropHide,            0   },
    { EShotPropEffectStart,     2   },
    { EShotPropEffectStop,      2   },
    { EShotPropPlacement,       1   },
    { EShotPropPlacementStart,  1   },
    { EShotPropPlacementKey,    1   },
    { EShotPropPlacementEnd,    1   }
};
const QSet<EShotActionType> NonAssetEShotActions = {
    EShotCam,
    EShotCamBlendStart,
    EShotCamBlendKey,
    EShotCamBlendEnd,
    EShotCamBlendTogame,
    EShotEnvBlendIn,
    EShotEnvBlendOut,
    EShotFadeIn,
    EShotFadeOut,
    EShotWorldAddfact,
    EShotWorldWeather,
    EShotWorldEffectStart,
    EShotWorldEffectStop
};

#endif // SHOTACTIONTYPES_H
